### ISSUE TITLE
Breeze Dark and Custom CSS on NextCloud 29 doesn't work 

### ISSUE THREAD

**Issue by MrPistachios** [dracula/nextcloud#3]
I'm trying to get the Dracula theme to work: https://draculatheme.com/nextcloud

This requires the Breeze Dark app, but after installing and adding the Dracula CSS, I don't see any changes.

I can see on GitHub that Breeze only supports NextCloud [versions 27 and 28.](https://i.imgur.com/UxPLWhm.png)

It makes sense that the new version has broken the Breeze app, but I was wondering if anyone had figured a way to apply custom CSS to v.29?

copied from reddit but I am having the same issue
https://www.reddit.com/r/NextCloud/comments/1ducjfy/breeze_dark_and_custom_css_on_nextcloud_29_doesnt/

**Comment by SIMULATAN** [comment]
Hi, sorry for the late response! Took a while to update nextcloud and I've been busy...

Anyway, I just reworked the theme using a different app: [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss).

If you can, please test if this suits your needs, if it does, I'll publish a new version.

## Instructions
1. Install the [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) Nextcloud App
2. Open the "Custom CSS" section in the "Theming" settings (`Administration Settings` -> `Theming`
3. Set the `Color` option to `#BD93F9`
4. Paste these styles into the `Custom CSS` text area:
```css
:root {
    --color-main-background: #282A36;
    --color-main-background-rgb: 40, 42, 54;
    --color-background-hover: #323440; /* main-background + 0x0A */
    --color-background-dark: #3A3C48; /* main-background + 0x12 */
    --color-background-darker: #4C4E5A; /* main-background + 0x24 */
    --color-placeholder-light: #44475A;
    --color-primary: #BD93F9;
    --color-primary-default: var(--color-primary);
    --color-primary-text: #F8F8F2;
    --color-primary-hover: #D1B3FB; /* primary, 30% lighter */
    --color-primary-element: var(--color-primary);
    --color-primary-element-hover: var(--color-primary-hover);
    --color-primary-element-text: var(--color-main-background); /* example: share symbol in folder icon */
    --color-background-plain: var(--color-main-background);
    --color-error: #FF5555;
    --color-error-rgb: 255, 85, 85;
    --color-error-hover: #FF8888;
    --color-error-text: #FF79C6;
    --color-warning: #F1FA8C;
    --color-warning-rgb: 241, 250, 140;
    --color-success: #50FA7B;
}
```
5. Click save


I don't actively use Nextcloud so I'd highly appreciate feedback and bug reports!
